"""Change file_size to BigInteger

Revision ID: c47c1ad3ac3f
Revises: f0fd65f83cc6
Create Date: 2025-03-09 21:11:37.584844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c47c1ad3ac3f'
down_revision = 'f0fd65f83cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_record', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_record', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
